version: '3.8'

services:
  api-gateway:
    build:
      context: ./service/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8085
      - USER_SERVICE_URL=http://user-service:8080
      - PRODUCT_SERVICE_URL=http://product-catalog-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083
      - CART_SERVICE_URL=http://shopping-cart-service:8084
    depends_on:
      - auth-service
      - user-service
      - product-catalog-service
      - inventory-service
      - order-service
      - shopping-cart-service

  auth-service:
    build:
      context: ./service/auth-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - USER_SERVICE_URL=http://user-service:8080
    depends_on:
      - user-service

  user-service:
    build:
      context: ./service/UserManagementService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  product-catalog-service:
    build:
      context: ./service/ProductCatalogService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  inventory-service:
    build:
      context: ./service/InventoryService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  order-service:
    build:
      context: ./service/OrderManagementService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PRODUCT_SERVICE_URL=http://product-catalog-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
    depends_on:
      - product-catalog-service
      - inventory-service

  shopping-cart-service:
    build:
      context: ./service/ShoppingCartService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PRODUCT_SERVICE_URL=http://product-catalog-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083
    depends_on:
      - product-catalog-service
      - inventory-service
      - order-service
