# Build stage
FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY shared/ ../shared/
COPY service/InventoryService/go.mod service/InventoryService/go.sum ./
RUN go mod download
COPY service/InventoryService/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o inventory ./cmd/server/main.go

# Run stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/inventory .
EXPOSE 8082
CMD ["./inventory"]
