# Build stage
FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY shared/ ../shared/
COPY service/OrderManagementService/go.mod service/OrderManagementService/go.sum ./
RUN go mod download
COPY service/OrderManagementService/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o order ./cmd/server/main.go

# Run stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/order .
EXPOSE 8083
CMD ["./order"]
