# Build stage
FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY shared/ ../shared/
COPY service/api-gateway/go.mod service/api-gateway/go.sum ./
RUN go mod download
COPY service/api-gateway/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./cmd/gateway/main.go

# Run stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/gateway .
EXPOSE 8000
CMD ["./gateway"]
